#! /bin/sh

export GTK_THEME=Adwaita-dark

# Definir o tema do cursor diretamente no bspwmrc (opcional)
export XCURSOR_THEME=Papirus-Dark
export XCURSOR_SIZE=24

pgrep -x sxhkd >/dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d . . . . . . . . . .

bspc config border_width 0
bspc config window_gap 8

bspc config split_ratio 0.52
#bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config border_width 2                 # espessura da borda
bspc config normal_border_color "#44475a"  # cor da borda normal
bspc config active_border_color "#8080c8"  # cor da janela ativa
bspc config focused_border_color "#8080c8" # cor da janela em foco

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd &
#picom --config /root/.config/picom/picom.conf &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
polybar &
darkman run &
xrandr --output DP-0 --primary --output HDMI-0 --right-of DP-0
feh --bg-fill ~/.wallpapers/bridge.png

